export { BotClientAdapter as BotClient } from "@/interfaces/BotClientAdapter"
export { ClientFactory as ClientFactoryInterface } from "@/interfaces/ClientFactory"
export { AppearableEntity } from "@/interfaces/AppearableEntity"
export { AppearableWatcher } from "@/interfaces/AppearableWatcher"
export { WatcherCompositor as WatcherCompositorInterface } from "@/interfaces/WatcherCompositor"
export { Command } from "@/interfaces/Command"
export { SlashCommand } from "@/interfaces/SlashCommand"
export { CommandProcessor } from "@/interfaces/CommandProcessor"
